---@param cutscene LegendCutscene
return function(cutscene)
    Game.legend.music:play("legend")
    cutscene:text("LET ME TELL YOU A PROPHECY,\n[wait:10]A PROPHECY THAT IS INEVITABLE.", "middle_bottom")
    cutscene:wait(3)
    cutscene:removeText()
    cutscene:text("AND AS THE ONE BEFORE ME, \n[wait:5]I SHALL TELL IT TO YOU.", "middle_bottom")
    cutscene:wait(3)
    cutscene:removeText()
    cutscene:text("BUT BEWARE.", "middle_bottom")
    cutscene:wait(2)
    cutscene:removeText()
    cutscene:text("THIS PROPHECY\nIS ONE OF\n[wait:20][color:purple]DESTRUCTON[color:reset]", "far_left")
    cutscene:wait(1)
    cutscene:text("THIS PROPHECY\nIS ONE OF\n[wait:20][color:yellow]SALVATION[color:reset]", "right")
    cutscene:wait(3)
    cutscene:removeText()
    cutscene:text("WITH A WORLD\nBLANKETED IN\n[wait:20][color:purple]DARKNESS[color:reset]", "far_left")
    cutscene:wait(1)
    cutscene:text("AWAITING FOR\nA SHINING\n[wait:20][color:yellow]LIGHT[color:reset]", "right")
    cutscene:wait(3)
    cutscene:removeText()

    cutscene:text("LET ME TELL YOU THE PROPHECY\n[wait:10]OF [color:yellow][wait:5]DELTA [wait:5]RUNE.[color:reset]", "middle_bottom")
    cutscene:wait(3)
    cutscene:removeText()

    Game.legend:addSlide("legend/spr_introimage1_0")
    cutscene:text("TWO SIDES, ONE OF LIGHT,[wait:10]\nAND ONE OF DARK.", "middle_bottom")
    cutscene:wait(3)
    cutscene:removeText()
    cutscene:text("LIVING IN HARMONY[wait:5].[wait:5].[wait:5].", "middle_bottom")
    cutscene:wait(3)
    cutscene:removeText()
    Game.legend:removeSlides()
    Game.legend:addSlide("legend/spr_introimage1_1")
    cutscene:text("HA HA HA[wait:5].[wait:5].[wait:5].\n[wait:10]HOW OBLIVIOUS THEY WERE.", "middle_bottom")
    cutscene:wait(3)
    cutscene:removeText()
    cutscene:text("THEY DIDN'T KNOW THAT THEIR\n[wait:2]FATES[wait:5] WERE ALREADY SEALED[wait:5].[wait:5].[wait:5].", "middle_bottom")
    cutscene:wait(4)
    cutscene:removeText()

    Game.legend:removeSlides()
    Game.legend:addSlide("legend/spr_introimage2_0")
    cutscene:text("A CALAMITY SO STRONG,[wait:10]\nTHAT THE BELLS RANG\nTHE DEATH'S TOLL.", "middle_bottom")
    cutscene:wait(4)
    cutscene:removeText()
    cutscene:text("IN DESPAIR, EVERYONE PRAYED.", "middle_bottom")
    cutscene:wait(4)
    cutscene:removeText()
    Game.legend:removeSlides()
    Game.legend:addSlide("legend/spr_introimage3_1")
    cutscene:text("AND THREE HEROES APPEARED\n[wait:10]AT WORLD'S EDGE.", "middle_bottom")
    cutscene:wait(4)
    cutscene:removeText()
    
    cutscene:text("TRYING TO STOP[wait:10]\nANGEL'S HEAVEN[wait:5].[wait:5].[wait:5].", "middle_bottom")
    cutscene:wait(4)
    cutscene:removeText()
    Game.legend:removeSlides()
    Game.legend:addSlide("legend/spr_introimage5_0")
    cutscene:text("THEY FOUGHT[wait:10]\nWITH EVERYTHING THEY COULD.", "middle_bottom")
    cutscene:wait(4)
    cutscene:removeText()
    cutscene:text("BUT THEY FAILED.", "middle_bottom")
    cutscene:wait(4)
    cutscene:removeText()

    Game.legend:removeSlides()
    cutscene:text("THEN THE WORLD\n[wait:10]WAS COVERED\n[wait:10]IN [color:purple]DARKNESS.[color:reset]", "middle_bottom")
    cutscene:wait(5)
    cutscene:removeText()
    
    cutscene:text("BUT[wait:5].[wait:5].[wait:5].", "middle_bottom")
    cutscene:wait(2)
    cutscene:removeText()
    cutscene:text("A SPARK OF HOPE WAS LIT,\n[wait:10]AS THE WORLD WAS RESTARTED.", "middle_bottom")
    cutscene:wait(4)
    cutscene:removeText()

    cutscene:text("HERE IS WHERE THREE NEW\n[wait:5]HEROES ARE CHOSEN.", "middle_bottom")
    cutscene:wait(4)
    cutscene:removeText()

    Game.legend:addSlide("legend/spr_introimage4_0")
    cutscene:text("A [color:yellow]SAVIOR,[color:reset]", "text_human")
    cutscene:wait(1)
    Game.legend:addSlide("legend/spr_introimage4_1")
    cutscene:text("A [color:red]DESTRUCTOR,[color:reset]", "text_monster")
    cutscene:wait(1)
    Game.legend:addSlide("legend/spr_introimage4_2")
    cutscene:text("AND A [color:purple]VESSEL.[color:reset]", "text_prince")
    cutscene:wait(3)
    cutscene:removeText()
    Game.legend:removeSlides()

    cutscene:text("WITH THIS,[wait:5] NEW HEROES,[wait:10]\nTHERE WAS A NEW\n[wait:5]FATED OBJECTIVE.", "middle_bottom")
    cutscene:wait(4)
    cutscene:removeText()
    cutscene:text("WHEN THE TIME COMES,[wait:10]\nSTOP THE [color:red]ROARING KNIGHT.[color:reset]", "middle_bottom")
    cutscene:wait(5)
    cutscene:removeText()
    cutscene:text("[color:purple]AND AT WORLD'S EDGE,[wait:10][color:reset]\n[color:purple]SHATTER THE TWILIGHT REVERIE.[color:reset]", "middle_bottom")
    cutscene:wait(3)
    cutscene:removeText()
    cutscene:text("FINALLY RESTORING THE BALANCE[wait:5]\nOF [color:yellow]LIGHT[color:reset][wait:5] AND [color:purple]DARK.[color:reset]", "middle_bottom")
    cutscene:wait(3)
    cutscene:removeText()
end